# Generated by Django 4.2.7 on 2023-12-02 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depart',
            fields=[
                ('departid', models.IntegerField(primary_key=True, serialize=False)),
                ('departname', models.CharField(max_length=50, verbose_name='部门名称')),
                ('count', models.IntegerField(verbose_name='人数')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='姓名')),
                ('password', models.CharField(default=None, max_length=10, verbose_name='密码')),
                ('age', models.IntegerField(null=True, verbose_name='年龄')),
                ('phonenum', models.IntegerField(null=True, verbose_name='手机号')),
                ('email', models.CharField(max_length=255, null=True, verbose_name='邮箱')),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.depart', verbose_name='关联部门')),
            ],
        ),
    ]
